#!/bin/bash
testSkim $CMSSW_BASE/src/Susy1LeptonAnalysis/Susy1LeptonSkimmer/data/TTJets_TuneCP5_RunIISummer19UL16NanoAODv2.root    "TTJets_TuneCP5_RunIISummer19UL16NanoAODv2" False False 2016 "m" "722.8" "1"  $1
testSkim $CMSSW_BASE/src/Susy1LeptonAnalysis/Susy1LeptonSkimmer/data/TTJets_TuneCP5_RunIISummer19UL16NanoAODAPVv2.root "TTJets_TuneCP5_RunIISummer19UL16NanoAODAPVv2" False False 2016 "m" "722.8" "1"  $1
