#!/bin/sh

#These steps are required on naf
module use -a /afs/desy.de/group/cms/modulefiles/;
module load cmssw;

cmsrel CMSSW_12_1_0
cd CMSSW_12_1_0/src
eval `scramv1 runtime -sh`;

git clone git@github.com:lucaswiens/Susy1LeptonSkimmer.git Susy1LeptonAnalysis/Susy1LeptonSkimmer

# Needed for JEC uncertainties but revelant files are copied to Susy1LeptonSkimmer
# This only needs to be checked out if you need to update the JEC uncertainty files
#git clone git@github.com:cms-jet/JECDatabase.git

# Muon Rocchester Corrections
git clone ssh://git@gitlab.cern.ch:7999/akhukhun/roccor.git RoccoR

# Library with corrections and scale factors in json format
git clone ssh://git@gitlab.cern.ch:7999/cms-nanoAOD/jsonpog-integration.git
gunzip jsonpog-integration/POG/*/*/*.json.gz

scram build -j 4
