#!/bin/sh
YEAR=${1}
# Recommended Samples with global tag: https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysis
# Missing SAMPLEs.. Use SAMPLE_TuneCP5_13TeV samples for now until more is available.

cd $CMSSW_BASE/src/Susy1LeptonAnalysis/Susy1LeptonSkimmer/data/samples/$YEAR

SAMPLELIST="TTJets_HT TTTo2L2Nu_TuneCP5_13TeV TTToSemiLeptonic_TuneCP5_13TeV WJetsToLNu_HT DYJetsToLL_M-50_HT DYJetsToLL_M-50_TuneCP5_13TeV QCD_HT ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV ST_s-channel_4f_leptonDecays_TuneCP5_13TeV TTZToNuNu_TuneCP5_13TeV-amcatnlo-pythia8 TTZToQQ_TuneCP5_13TeV TTWJetsToLNu_TuneCP5_13TeV TTWJetsToQQ_TuneCP5_13TeV tZq_ll_4f_ckm_NLO_TuneCP5 WWTo2L2Nu_TuneCP5_13TeV WW_TuneCP5_13TeV WZ_TuneCP5_13TeV ZZ_TuneCP5_13TeV ZZTo2L2Nu WWToLNuQQ WZTo1L1Nu2Q WZTo1L3Nu WZTo2L2Q ZZTo2Q2Nu ZZTo2Q2L"

#SAMPLELIST="ST_tW ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV"
for SAMPLE in $SAMPLELIST
do
	echo $SAMPLE
	echo \#${SAMPLE} > ${SAMPLE}.txt
	if [ ${YEAR} == "2016preVFP" ]; then
		#GLOBALTAG=106X_mcRun2_asymptotic_preVFP_v11
		GLOBALTAG=106X_mcRun2_asymptotic_preVFP
		dasgoclient -query="dataset=/${SAMPLE}*/RunIISummer20UL16*NanoAODv9-${GLOBALTAG}*/NANOAODSIM" | grep -v BGenFilter >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2016postVFP" ]; then
		#GLOBALTAG=106X_mcRun2_asymptotic_v17
		GLOBALTAG=106X_mcRun2_asymptotic
		dasgoclient -query="dataset=/${SAMPLE}*/RunIISummer20UL16*NanoAODv9-${GLOBALTAG}*/NANOAODSIM" | grep -v BGenFilter >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2017" ]; then
		#GLOBALTAG=106X_mc2017_realistic_v10
		GLOBALTAG=106X_mc2017_realistic
		dasgoclient -query="dataset=/${SAMPLE}*/RunIISummer20UL17*NanoAODv9-${GLOBALTAG}*/NANOAODSIM" | grep -v BGenFilter >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2018" ]; then
		#GlOBALTAG=106X_upgrade2018_realistic_v16_L1v1
		GlOBALTAG=106X_upgrade2018_realistic_v16_L1
		dasgoclient -query="dataset=/${SAMPLE}*/RunIISummer20UL18*NanoAODv9-${GLOBALTAG}*/NANOAODSIM" | grep -v BGenFilter >> ${SAMPLE}.txt
	else
		echo "INVALID YEAR ${YEAR}! Use 2016preVFP, 2016postVFP, 2017 or 2018!"
		exit
	fi
done

cat $(echo ${SAMPLELIST} | sed "s/ /.txt /g").txt > MC.txt

for SAMPLE in SingleMuon SingleElectron MET
do
	#dataset=/SingleElectron/Run2016*UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD
	echo \#${SAMPLE} > ${SAMPLE}.txt
	if [ ${YEAR} == "2016preVFP" ]; then
		dasgoclient -query="dataset=/${SAMPLE}*/Run${YEAR::4}*UL${YEAR::4}*NanoAODv9*/NANOAOD" | grep -v JME | grep -v GT36 >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2016postVFP" ]; then
		echo "#For data, run BCDEF are preVFP and FGH are postVFP. Run F is split, 31 sample are pre, 7 are post.. But this depends on run number, thus it will be handled later." >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2017" ]; then
		dasgoclient -query="dataset=/${SAMPLE}*/Run${YEAR}*UL${YEAR}*NanoAODv9*/NANOAOD" | grep -v JME | grep -v GT36 >> ${SAMPLE}.txt
	elif [ ${YEAR} == "2018" ]; then
		dasgoclient -query="dataset=/${SAMPLE}*/Run${YEAR}*UL${YEAR}*NanoAODv9*/NANOAOD" | grep -v JME | grep -v GT36 >> ${SAMPLE}.txt
	else
		echo "INVALID YEAR ${YEAR}! Use 2016preVFP, 2016postVFP, 2017 or 2018!"
		exit
	fi
done

cat SingleMuon.txt SingleElectron.txt MET.txt > Data.txt
