#!/bin/bash
mkdir -p $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT
cd $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT

INFILE=$1
ISDATA=$2
ERA=$3
OUT=$4
JOB=$5
RUNPERIOD=$6
NMAXEVENTS=$7

##Do the skimming
NanoSkim $INFILE $ISDATA "$ERA" $XSEC ${OUT}_${JOB}.root $RUNPERIOD $NMAXEVENTS
