#!/bin/bash
source /etc/profile
source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/grid.desy.de/etc/profile.d/grid-ui-env.sh

module use -a /afs/desy.de/group/cms/modulefiles/
module load cmssw
cd $8 #For now this is hardcoded
export SCRAM_ARCH=slc6_amd64_gcc700
eval `scramv1 runtime -sh` #cmsenv

#export X509_USER_PROXY=$HOME/.globus/x509up
export X509_USER_PROXY=/nfs/dust/cms/user/wiens/x509up

#Split the input file name for xSec function
INFILE=$1
ISDATA=$2
ERA=$3
XSEC=$4
OUT=$5
JOB=$6
RUNPERIOD=$7

cd $TMP
$xrdcp $1 nanoFile.root

#Do the skimming
NanoSkim nanoFile.root $ISDATA "$ERA" $XSEC ${OUT}_${JOB}.root $RUNPERIOD

rm $INFILE
mkdir -p $CMSSW_BASE/Skimming/`date +"%Y_%m_%d"`/$OUT
mv ${OUT}_${JOB}.root $CMSSW_BASE/Skimming/`date +"%Y_%m_%d"`/$OUT
