#!/bin/bash
MERGEDIR=${PWD##*/}
DIRNUM=1
MAXSIZE=2000000000

for FILE in *.root; do
	if [ `du -b -s "${FILE}" | cut -f 1` -gt ${MAXSIZE} ]; then
		echo ${FILE} is too big for a single folder, skipping
		continue
	fi
	if [ ! -d "${MERGEDIR}_${DIRNUM}" ]; then
		echo creating directory ${MERGEDIR}_${DIRNUM}
		mkdir "${MERGEDIR}_${DIRNUM}"
	fi
	if [ `du -b -s "${MERGEDIR}_${DIRNUM}" | cut -f 1` -gt ${MAXSIZE} ]; then
		echo ${MERGEDIR}_${DIRNUM} has reached ${MAXSIZE}
		let "DIRNUM += 1"
		if [ ! -d "${MERGEDIR}_${DIRNUM}" ]; then
			echo creating directory ${MERGEDIR}_${DIRNUM}
			mkdir "${MERGEDIR}_${DIRNUM}"
		fi
		mv "${FILE}" "${MERGEDIR}_${DIRNUM}"
	else
		mv "${FILE}" "${MERGEDIR}_${DIRNUM}"
	fi
done

mkdir -p ../../merged/${MERGEDIR}
for DIR in *; do
	echo Merging files in ${DIR}
	hadd ${DIR}_merged.root ${DIR}/*.root
	mv ${DIR}_merged.root ../../merged/${MERGEDIR}
	#mv ${DIR}/*root .
	#rm -rf ${DIR}
done
