#!/bin/bash
MERGEDIR=${PWD##*/}
DIRNUM=1
MAXSIZE=1000000000

for FILE in *.root; do
	if [ `du -b -s "${FILE}" | cut -f 1` -gt ${MAXSIZE} ]; then
		echo ${FILE} is too big for a single folder, skipping
		continue
	fi
	if [ ! -d "${MERGEDIR}_${DIRNUM}" ]; then
		echo creating directory ${MERGEDIR}_${DIRNUM}
		mkdir "${MERGEDIR}_${DIRNUM}"
	fi
	if [ `du -b -s "${MERGEDIR}_${DIRNUM}" | cut -f 1` -gt ${MAXSIZE} ]; then
		echo ${MERGEDIR}_${DIRNUM} has reached ${MAXSIZE}
		let "DIRNUM += 1"
		if [ ! -d "${MERGEDIR}_${DIRNUM}" ]; then
			echo creating directory ${MERGEDIR}_${DIRNUM}
			mkdir "${MERGEDIR}_${DIRNUM}"
		fi
		mv "${FILE}" "${MERGEDIR}_${DIRNUM}"
	else
		mv "${FILE}" "${MERGEDIR}_${DIRNUM}"
	fi
done

for DIR in *; do
	cd ${DIR}
	echo Merging files in ${DIR}
	hadd ${DIR}_merged.root *
	mv ${DIR}_merged.root ..
	cd ..
done

echo Moving all merged files to ../../merged/${PWD##*/}
mkdir -p ../../merged/${PWD##*/}
mv *_merged.root ../../merged/${PWD##*/}
