#!/bin/bash
source /etc/profile
source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/grid.desy.de/etc/profile.d/grid-ui-env.sh

module use -a /afs/desy.de/group/cms/modulefiles/
module load cmssw
cd $9
export SCRAM_ARCH=slc6_amd64_gcc700
eval `scramv1 runtime -sh` #cmsenv

export X509_USER_PROXY=/nfs/dust/cms/user/wiens/x509up

INFILE=$1
ISDATA=$2
DOSYSTEMATICS=$3
ERA=$4
XSEC=$5
OUT=$6
JOB=$7
RUNPERIOD=$8

cd $TMP
#Do the skimming
NanoSkim $INFILE $ISDATA $DOSYSTEMATICS $ERA $XSEC ${OUT}_${JOB}.root $RUNPERIOD

mkdir -p $CMSSW_BASE/Skimming/`date +"%Y_%m_%d"`/$OUT
mv ${OUT}_${JOB}.root $CMSSW_BASE/Skimming/`date +"%Y_%m_%d"`/$OUT
