#!/bin/bash

export X509_USER_PROXY=/nfs/dust/cms/user/${USER}/x509up
if ! test -f $X509_USER_PROXY ; then
	echo "Grid certificate not found at: $X509_USER_PROXY"
	echo "Exiting now.."
	exit
fi

INFILE=$1
OUT=$2
ERA=$3
RUNPERIOD=$4
ISFASTSIM=$5
XSECTION=$6
JOB=$7
BASEDIR=$8
OUTPUTDIR=$9
echo INFILE         $INFILE
echo OUT            $OUT
echo ERA            $ERA
echo RUNPERIOD      $RUNPERIOD
echo ISFASTSIM      $ISFASTSIM
echo XSECTION       $XSECTION
echo JOB            $JOB
echo BASEDIR        $BASEDIR
echo OUTPUTDIR      $OUTPUTDIR

echo "Processing ${INFILE} for Job ${OUT}_${JOB}"

source /etc/profile
source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/grid.desy.de/etc/profile.d/grid-ui-env.sh

module use -a /afs/desy.de/group/cms/modulefiles/
module load cmssw
cd ${BASEDIR}
eval `scramv1 runtime -sh` #cmsenv

# Do the skimming
#cd ${OUTPUTDIR}
#echo NanoSkim ${INFILE} ${OUT}_${JOB}.root ${ERA} ${RUNPERIOD} ${XSECTION}
#NanoSkim ${INFILE} ${OUT}_${JOB}.root ${ERA} ${RUNPERIOD} ${XSECTION}

# Copy the input file and run over it
cd /tmp #${TMP}

xrdcp ${INFILE} inputFile_${JOB}.root || exit

#Do the skimming
cd ${OUTPUTDIR}
echo NanoSkim /tmp/inputFile_${JOB}.root ${OUT}_${JOB}.root ${ERA} ${RUNPERIOD} ${ISFASTSIM} ${XSECTION}
NanoSkim /tmp/inputFile_${JOB}.root ${OUT}_${JOB}.root ${ERA} ${RUNPERIOD} ${ISFASTSIM} ${XSECTION}

rm /tmp/inputFile_${JOB}.root
