#!/bin/sh
#Do not overwrite any of the old arguments.md, instead create a new one
eval "DEST=arguments.md"
if [ -e "$DEST" ] && ! [ -d "$DEST" ];then
	PREFIX=${DEST%.*}
	COUNT=1
	args= i=1
	while [ $i -lt $# ]; do args="$args \"\${$i}\"" i=$((i+1)); done
	DEST="arguments"$(printf "%03d" $COUNT)".md"
	while [ -e "$DEST" ];do
		COUNT=$((COUNT+1))
		DEST="arguments"$(printf "%03d" $COUNT)".md"
	done
fi

#Look for failed jobs and find the arguments of this job.
#Create a new arguments file
for arg in $(for out in $(
	grep -r "return value" logs |
	grep -v "return value 0" |
	awk -F: '{printf $1 "\n"}' |
	uniq |
	sed "s@error@output@g" |
	sed "s@stderr@stdout@g"
	)
	do
		grep Processing $out |
		awk '{printf $2 "\n"}'
	done
)
do
	grep $arg arguments.md >> $DEST
done

#Create a new submit file using the new arguments file in the queue statement
cp condor.submit re.submit
sed -i "s@arguments\.md@${DEST}@g" re.submit
