#!/bin/bash
INFILE=$1
ISDATA=$2
DOSYSTEMATICS=$3
ERA=$4
XSEC=$5
OUT=$6
JOB=$7
RUNPERIOD=$8
NMAXEVENTS=$9

mkdir -p $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT
cd $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT

##Do the skimming
NanoSkim $INFILE $ISDATA $DOSYSTEMATICS $ERA $XSEC ${OUT}_${JOB}.root $RUNPERIOD $NMAXEVENTS
