#!/bin/bash
INFILE=$1
OUT=$2
ISDATA=$3
DOSYSTEMATICS=$4
ERA=$5
RUNPERIOD=$6
XSECTION=$7
JOB=$8
NMAXEVENTS=$9

mkdir -p $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT
cd $CMSSW_BASE/Testing/`date +"%Y_%m_%d"`/$OUT

##Do the skimming
NanoSkim ${INFILE} ${OUT}_${JOB}.root $ISDATA $DOSYSTEMATICS $ERA $RUNPERIOD $XSECTION $NMAXEVENTS
